blog/templates/main.html, blog/templates/maintwo.html
=> wordcloud_change

blog/apps.py, blog/documents.py, blog/logging.py, blog/middleware.py, blog/templates/main.html, blog/urls.py, blog/views.py, docker-compose.yml, final/settings.py
=> log collection - if you log in

blog/templates/mypage.html
=> mypage create

blog/templates/ds_detail.html, blog/templates/main.html
=> header,footer change

blog/templates/ds_detail.html, blog/templates/mypage.html
=> header,footer final

blog/templates/login.html
=> login change

blog/templates/main.html, blog/views.py
=> main, veiws

blog/templates/main.html, blog/views.py
=> main css final

blog/templates/login.html
껍데기는 다 만들었슴다..
이미지 변경이랑 링크연결 부탁드려요-!
=> login front final

blog/templates/join_agree.html
명준님 조인어그리 껍데기 만들엇슴다
확인 부탁드려요
감사합니다~~
=> join_agree front final

blog/templates/join_agree.html
=> join_agree front final_FINAL

blog/templates/savings_info1.html
=> static 수정?

accounts/templates/accounts/join_agree.html, accounts/templates/accounts/login.html, accounts/templates/accounts/signup.html
login 
join_agree 
signup 
위 세 파일의 html 프론트 수정했습니다-!
이용약관에서 동의 체크 안해도 가입하기로 넘어가는 부분을 수정 부탁드려요!!
감사합니다~~
=> login join_agree signup 최종수정완

blog/templates/savings_info1.html, blog/views.py
오전 변경은 그 saving_info 4개 페이지 다 합치는 거라서 따로 다른 페이지에 하고 있어요...
최대한 함수는 안고치고 그대로 두려고 하는데 그래도 다 끝나면 연결 좀 손 봐야할 것 같아유
감사....
=> view, savings_info 조금 수정... 이미지 불러오는 경로 수정

blog/templates/loginmain.html, blog/templates/report_origin.html
=> report_origin_header_change

accounts/templates/accounts/login.html, blog/templates/spending_mbti.html
spending_mbti front 중간 push임니다,,
데이터 집어넣고
세부 디자인 수정하면
완성이 되겠지요...??
=> spending_mbti front 중간 push

blog/templates/check_box.html
모델에 필요한 선택사항 입력받는 html 생성... test라 디자인은 안함.
=> test_html 생성

blog/templates/report_origin.html, blog/templates/spending_mbti.html
아직 데이터 안 들어간 페이지들이 있어서
컨텐츠 다 들어가면 추후 디테일 수정 예정입니다-!
=> 나경은 프론트 부분 마무리

blog/templates/loginmain.html, blog/views.py, models.py
Reverts Coke-Eating-Polarbear/fisa_share#51
=> Revert "몰루?"

blog/templates/recommend_savings_top5.html, static/css/recommend_savings_top5.css
=> recommend_savings_top5 기존 상품 박스 추가

blog/templates/spending_mbti.html, blog/views.py
eat : 식비
transfer : 교통비
utility : 공과금
phone : 통신비
home : 주거비
hobby : 여가/취미
fashion : 패션/잡화
party : 모임회비
allowance : 경조사
study : 교육비
medical : 의료비
=> alter spendong mbti korean mapping

blog/templates/better_options.html, blog/templates/recommend_savings_top5.html, static/css/better_options.css
top5에 추가했던 기존상품 박스 better_options로 옮겼습니다~~~
=> top5,better_options 수정

blog/templates/report_origin.html, static/css/report_origin.css
=> 금융리포트 화면 완료

blog/templates/ds_detail.html, blog/templates/mypage.html, static/css/ds_detail.css, static/css/mypage.css
=> 마이페이지 및 상품 자세히보기 페이지 완성

blog/templates/d_detail.html, blog/templates/s_detail.html, static/css/ds_detail.css
merege merege merege merege merege please
=> 자세히보기 약관 완료

blog/models.py, blog/templates/mypage.html, blog/views.py, static/css/mypage.css
머지 부탁해요...
목표 소비액 연결하고, 디자인 수정했어요...
=> mypage_목표소비액 연결

blog/templates/better_options.html, blog/templates/recommend_savings_top5.html, blog/templates/report_origin.html, blog/templates/spending_mbti.html, static/css/better_options.css, static/css/header.css, static/css/recommend_savings_top5.css, static/css/report_origin.css, static/css/spending_mbti.css
btter top5 report mbti 헤더 풋터 수정
=> btter top5 report mbti 헤더 풋터 수정

blog/templates/loginmain.html, blog/templates/mypage.html, blog/templates/recommend_savings_top5.html, blog/views.py
=> 메인페이지 금융리포트 연결

blog/templates/better_options.html, blog/templates/d_detail.html, static/css/ds_detail.css
=> 자세히보기 최종수정

blog/templates/mypage.html, blog/templates/spending_mbti.html
=> 마이페이지 만기일 수정

blog/templates/mypage.html
=> mypage_예/적금 부분 변경

blog/templates/better_options.html, blog/templates/recommend_savings_top5.html, static/css/better_options.css, static/css/recommend_savings_top5.css
=> 페이지 세부사항 수정중_1

blog/templates/recommend_savings_top5.html, blog/templates/report_origin.html, static/css/recommend_savings_top5.css
=> top3 타이틀 수정

blog/templates/better_options.html, blog/templates/mypage.html, static/css/better_options.css, static/css/mypage.css
=> mypage 디자인 수정

static/css/ds_detail.css
=> d_dtail 조정 조금....?

blog/templates/d_detail.html, blog/templates/main.html, static/css/ds_detail.css
=> ds_detail 헤더 수정

blog/templates/d_detail.html, static/css/ds_detail.css
=> 자세히보기 사진수정

blog/templates/better_options.html, blog/templates/d_detail.html, blog/templates/loginmain.html, blog/templates/mypage.html, blog/templates/recommend_savings_top5.html, blog/templates/report_ex.html, blog/templates/report_origin.html, blog/templates/s_detail.html, blog/templates/savings_info.html, blog/templates/spending_mbti.html, static/css/loginmain.css
=> 신규적금추천->신규상품추천

blog/templates/better_options.html, blog/templates/d_detail.html, blog/templates/loginmain.html, static/css/better_options.css, static/css/ds_detail.css, static/css/loginmain.css
merege해 주세용~
'자세히버튼' 제거하고 상품 카드에 커서 가져가면 확대 밑 그림자, 연결
=>  상품 선택 디테일 변경

blog/templates/loginmain.html, blog/templates/search.html, blog/urls.py, blog/views.py, static/css/search.css
=>  상품검색페이지 초안

blog/templates/search.html
=> search 수정1

blog/templates/search.html, static/css/search.css
=> search front

blog/templates/search.html
=> search 키워드 추가
